# Generated by Django 5.2.6 on 2025-09-14 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="matcher.artist",
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="songs",
                to="matcher.album",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="matcher.artist",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="album",
            unique_together={("artist", "title")},
        ),
        migrations.AlterUniqueTogether(
            name="song",
            unique_together={("title", "artist", "album")},
        ),
        migrations.AlterUniqueTogether(
            name="songgenre",
            unique_together={("song", "genre")},
        ),
    ]
