# Generated by Django 5.2.6 on 2025-12-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="audio_features",
        ),
        migrations.AddField(
            model_name="song",
            name="lyrics",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="emotion",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="duration_sec",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="platform",
            field=models.CharField(default="spotify", max_length=50),
        ),
        migrations.AlterField(
            model_name="songemotion",
            name="confidence",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="songemotion",
            name="source",
            field=models.CharField(default="manual_import", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="songemotion",
            unique_together={("song", "emotion")},
        ),
        migrations.AlterModelTable(
            name="album",
            table="albums",
        ),
        migrations.AlterModelTable(
            name="artist",
            table="artists",
        ),
        migrations.AlterModelTable(
            name="emotion",
            table="emotions",
        ),
        migrations.AlterModelTable(
            name="song",
            table="songs",
        ),
        migrations.AlterModelTable(
            name="songemotion",
            table="song_emotions",
        ),
    ]
