# Generated by Django 5.2.6 on 2025-11-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="cover_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
