# Generated by Django 5.2.6 on 2025-09-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0002_alter_album_artist_alter_artist_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="genres",
            field=models.ManyToManyField(
                related_name="songs", through="matcher.SongGenre", to="matcher.genre"
            ),
        ),
    ]
