# Generated by Django 5.2.6 on 2025-11-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0002_album_cover_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="audio_features",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
