# Generated by Django 5.2.6 on 2025-09-14 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0003_alter_song_genres"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "db_table": "emotions",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="idx_emotion_name")],
            },
        ),
        migrations.CreateModel(
            name="SongEmotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                (
                    "source",
                    models.CharField(
                        choices=[("ml", "ML"), ("rule", "Rule"), ("manual", "Manual")],
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "emotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emotion_songs",
                        to="matcher.emotion",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_emotions",
                        to="matcher.song",
                    ),
                ),
            ],
            options={
                "db_table": "song_emotions",
                "ordering": ["song_id", "emotion_id"],
                "indexes": [
                    models.Index(fields=["song"], name="idx_se_song"),
                    models.Index(fields=["emotion"], name="idx_se_emotion"),
                    models.Index(fields=["source"], name="idx_se_source"),
                ],
                "unique_together": {("song", "emotion")},
            },
        ),
    ]
