# Generated by Django 5.2.6 on 2025-09-14 22:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0004_emotion_songemotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("suspended", "suspended")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="idx_users_email"),
                    models.Index(fields=["username"], name="idx_users_username"),
                    models.Index(fields=["status"], name="idx_users_status"),
                ],
            },
        ),
    ]
